# 日志级别
logging:
  level: 4
  filename: /var/log/perfmonitorscan/backend/backend.log
  log_num: 20
  max_size: 1000000
  compress: true

database:
  database: "es"  # 支持的类型: sqlite, mysql, postgresql
  username:
  password:
  host: "localhost"
  port: "9200"
  dbname: "monitoring"