# 日志级别
logging:
  level: 4
  filename: ../agent.log
  log_num: 20
  max_size: 1000000
  compress: true

database:
  database: "mysql"  # 支持的类型: sqlite, mysql, postgresql
  user: "root"
  password: "password"
  host: "localhost"
  port: "3306"
  dbname: "monitoring"